train: ..\..\..\Datasets\Deepfish\train\images
val: ..\..\..\Datasets\Deepfish\val\images
test: ..\..\..\Datasets\Deepfish\test\images

nc: 23
names: [
  'Caranx_sexfasciatus',
  'F1', 
  'F2',
  'F3', 
  'F4',
  'F5',
  'F6',
  'F7',
  'Acanthopagrus_palmaris',
  'Lutjanus_russellii',
  'acanthopagrus_and_caranx',
  'acanthopagrus_palmaris', 
  'Gerres',
  'Caranx',
  'Amniataba_caudivittatus',
  'gerres_2',
  'gerres',
  'Epinephelus',
  'Fish',
  'juvenile',
  'palmaris',
  'EJP',
  'caudivittatus'
]
